--システム制御 - システム変数
CREATE TABLE ZT010(
     IDVARIANT CHAR(20) NOT NULL COMMENT '変数ＩＤ',
     TXNAME CHAR(10) NOT NULL COMMENT '変数名',
     TXTYPE CHAR(10) NOT NULL COMMENT '変数値タイプ',
     TXVALUE CHAR(100) NOT NULL COMMENT '変数値',
     TXREMARKS VARCHAR(300) COMMENT '摘要',
CONSTRAINT ZT010_PK PRIMARY KEY (IDVARIANT)
);

