--システム制御 - ユーザ
CREATE TABLE ZT020(
     IDUSER CHAR(10) NOT NULL COMMENT 'ユーザＩＤ',
     TXNAME CHAR(30) NOT NULL COMMENT '漢字名',
     TXPASSWORD CHAR(30) NOT NULL COMMENT 'パスワード',
CONSTRAINT ZT020_PK PRIMARY KEY (IDUSER)
);